version: '3.2'

services:

  server:
    build:
      context: .
      dockerfile: ./services/fpm/Dockerfile
    volumes:
      - ./src/:/var/www/app
    env_file:
      - ./services/fpm/environments/.env
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: ./services/nginx/Dockerfile
    volumes:
      - ./src/:/var/www/app
    ports:
      - "8000:8000"
    depends_on:
      - server

  db:
    image: mariadb:10.2.19
    restart: on-failure
    ports:
      - "33061:3306"
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: you-compilations
      MYSQL_USER: you-compilations
      MYSQL_PASSWORD: 12345

  queue:
    build:
      context: .
      dockerfile: ./services/queue/Dockerfile
    restart: on-failure
    volumes:
      - ./src/:/var/www/app
    env_file:
      - ./services/fpm/environments/.env
    depends_on:
      - server

networks:
  default:

volumes:
  database: