version: '3.7'

services:

  server:
    build:
      context: .
      dockerfile: ./docker/app.fpm.dockerfile
    env_file:
      - ./docker/compose-env/.env
    volumes:
      - ./src/:/var/www/app
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.fpm.dockerfile
    volumes:
      - ./src/:/var/www/app
    ports:
      - "8000:8000"
    depends_on:
      - server

  db:
    image: mariadb:10.3
    restart: on-failure
    ports:
      - "33061:3306"
    volumes:
      - ./.database:/var/lib/mysql
    env_file:
      - ./docker/compose-env/.db

  queue:
    build:
      context: .
      dockerfile: ./docker/app.queue.dockerfile
    restart: on-failure
    volumes:
      - ./src/:/var/www/app
    env_file:
      - ./docker/compose-env/.env
    depends_on:
      - server

networks:
  default:
    name: you-compilations